### PR TITLE
Adding podcast links

### PR DESCRIPTION
**Pull request by jakelacey2012**
## Changes
- Adds `.gitignore` to exclude the vendor directory, unsure why this isn't in there already.
- Adding Spotify podcast link.

### CODE REVIEW

**Comment by jakelacey2012** [comment]
I've published the podcast to google but we need to wait a couple of days
> If this is a new show in Podcasts Manager, wait a few days for Google to start serving your podcast and accumulating data. If this is an existing show, read how to troubleshoot this issue.

**Comment by jakelacey2012** [comment]
Apple podcast is a right pain, we should probably use the offbyone email for that one I reckon to create an apple account what do you think?

**Comment by g105b** [comment]
> vendor directory, unsure why this isn't in there already
I have /vendor in my global gitignore file because I'm mainly in PHP projects. Will take note.

> create an apple account
this doesn't sound like a fun activity, but yeah I think we should use the contact@ email... or apple@ ?

**Comment by jakelacey2012** [comment]
> this doesn't sound like a fun activity, but yeah I think we should use the contact@ email... or apple@ ?

Just having a look at that now.

**Comment by jakelacey2012** [comment]
Screenshot 2021-05-16 at 17 45 31

The extra security with an account is a bit of a pain too, we'll need to get a podcast phone now hahah :P

**Pull request merged**
